name: 'New Github User Projects as Rss feeds'
description: 'Provide a description here'
author: 'Stefan Breitenstein'
inputs:
  state:
    required: true
    description: 'state as json'
    default: '{}'
  feedUrl:
    required: true
    description: 'url where the feed can be found'
  names:
    required: true
    description: 'list of names'
  retention:
    required: true
    description: 'how long should an entry be retained'
    default: '200'
  title:
    required: true
    description: 'title for the json feed'
    default: 'GH-User Projects'
outputs:
  state:
    description: 'State for the action. Needs to be added in the next run'
  jsonFeed:
    description: 'created jsonFeed from the previous state and the new fetched data'
runs:
  using: 'node16'
  main: 'dist/index.js'
